sulu_product.get_products:
    path: /products.{_format}
    methods: GET
    controller: sulu_product.admin_product_details_controller::cgetAction
    format: json

sulu_product.get_product:
    path: /products/{id}.{_format}
    methods: GET
    controller: sulu_product.admin_product_details_controller::getAction
    format: json

sulu_product.post_product:
    path: /products.{_format}
    methods: POST
    controller: sulu_product.admin_product_details_controller::postAction
    format: json

sulu_product.put_product:
    path: /products/{id}.{_format}
    methods: PUT
    controller: sulu_product.admin_product_details_controller::putAction
    format: json

sulu_product.delete_product:
    path: /products/{id}.{_format}
    methods: DELETE
    controller: sulu_product.admin_product_details_controller::deleteAction
    format: json

sulu_product.get_product_content:
    path: /product-contents/{id}.{_format}
    methods: GET
    controller: sulu_product.admin_product_content_controller::getAction
    format: json

sulu_product.put_product_content:
    path: /product-contents/{id}.{_format}
    methods: PUT
    controller: sulu_product.admin_product_content_controller::putAction
    format: json

sulu_product.post_product_content_trigger:
    path: /product-contents/{id}.{_format}
    methods: POST
    controller: sulu_product.admin_product_content_controller::postTriggerAction
    format: json

sulu_product.get_product_versions:
    path: /product-contents/{id}/versions.{_format}
    methods: GET
    controller: sulu_product.admin_product_content_controller::getVersionsAction
    format: json

sulu_product.get_measurement_families:
    path: /measurement-families.{_format}
    methods: GET
    controller: sulu_product.admin_measurement_family_controller::cgetAction
    format: json

sulu_product.get_measurement_family:
    path: /measurement-families/{id}.{_format}
    methods: GET
    controller: sulu_product.admin_measurement_family_controller::getAction
    format: json

sulu_product.get_measurement_units:
    path: /measurement-units.{_format}
    methods: GET
    controller: sulu_product.admin_measurement_unit_controller::cgetAction
    format: json

sulu_product.get_measurement_unit:
    path: /measurement-units/{id}.{_format}
    methods: GET
    controller: sulu_product.admin_measurement_unit_controller::getAction
    format: json

sulu_product.get_attributes:
    path: /attributes.{_format}
    methods: GET
    controller: sulu_product.admin_attribute_details_controller::cgetAction
    format: json

sulu_product.get_attribute:
    path: /attributes/{id}.{_format}
    methods: GET
    controller: sulu_product.admin_attribute_details_controller::getAction
    format: json

sulu_product.post_attribute:
    path: /attributes.{_format}
    methods: POST
    controller: sulu_product.admin_attribute_details_controller::postAction
    format: json

sulu_product.put_attribute:
    path: /attributes/{id}.{_format}
    methods: PUT
    controller: sulu_product.admin_attribute_details_controller::putAction
    format: json

sulu_product.delete_attribute:
    path: /attributes/{id}.{_format}
    methods: DELETE
    controller: sulu_product.admin_attribute_details_controller::deleteAction
    format: json

sulu_product.get_attribute_groups:
    path: /attribute-groups.{_format}
    methods: GET
    controller: sulu_product.admin_attribute_group_details_controller::cgetAction
    format: json

sulu_product.get_attribute_group:
    path: /attribute-groups/{id}.{_format}
    methods: GET
    controller: sulu_product.admin_attribute_group_details_controller::getAction
    format: json

sulu_product.post_attribute_group:
    path: /attribute-groups.{_format}
    methods: POST
    controller: sulu_product.admin_attribute_group_details_controller::postAction
    format: json

sulu_product.put_attribute_group:
    path: /attribute-groups/{id}.{_format}
    methods: PUT
    controller: sulu_product.admin_attribute_group_details_controller::putAction
    format: json

sulu_product.delete_attribute_group:
    path: /attribute-groups/{id}.{_format}
    methods: DELETE
    controller: sulu_product.admin_attribute_group_details_controller::deleteAction
    format: json
